app/models/recipe.py
from app import db 

class Recipe(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement= True)
    name = db.Column(db.String)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import os
from dotenv import load_dotenv


db = SQLAlchemy()
migrate = Migrate()
load_dotenv()


def create_app():
    app = Flask(__name__)
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.static_folder = 'static'

    from app.models.recipe import Recipe

    db.init_app(app)
    migrate.init_app(app, db)

    from .routes import recipes_bp
    app.register_blueprint(recipes_bp, url_prefix="/recipes")


    return app

app/routes.py
from flask import Blueprint, make_response, jsonify, abort, request, render_template
from app import db
from app.models.recipe import Recipe
import os
import requests
import json


recipes_bp = Blueprint("recipe", __name__, url_prefix= "/recipes")
def validate_input(input):
    try: 
        input.isalpha()
    except:
        abort(make_response({"details": "Invalid Data"}, 400))
    
    return str(input.capitalize())

@recipes_bp.route("/")
def welcome():
    ingredient = request.args.get("ingredient")
    if ingredient:
        return get_recipe_search(ingredient)
    else:
        return render_template('index.html')

def get_recipe_search(ingredient):
    path= "https://api.edamam.com/search"

    app_key= os.environ.get('API_KEY')
    app_id= os.environ.get('API_ID')
    q = validate_input(ingredient)
    
    recipe_list= []
    response = requests.get(f"https://api.edamam.com/search?q={q}&app_id={app_id}&app_key={app_key}")
    recipes_hits = response.json()["hits"]


    for recipe in recipes_hits: 
        recipe_list.append(recipe["recipe"])

    return render_template("recipes.html", recipes=recipe_list, ingredient=q)

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='index.css') }}" />
    <title>Recipes</title>
</head>
<body class="background" style="background-image: url(../static/assets/main-food.jpeg);">
    <header>
        <h1 class="title">Curious Appetite</h1>
    </header>
    <section class="search_bar" >
        <form action ="/recipes">
            <label for="ingredient">Find Some Recipes</label><br>
            <input type="text" id="searchbox" name="ingredient" placeholder="Search"><br>
            <input id="searchbutton" type="submit">
        </form>
    </section>
</body>
</html>

app/templates/recipes.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='recipes.css')}}" />
    <title>Recipe_Cards</title>
</head>

<body>
    <h2 class="header">Recipes with {{ingredient}}</h2>
    <h3 class="return_home"> 
        <a href="{{url_for('recipe.welcome')}}">Home</a>
    </h3>
    <section class="recipe_card">
    {% for recipe in recipes %}
        <h3 class="recipe_title">{{recipe.label.title()}}</h3>
        <p class="yields">
            Yields {{recipe.yield}} Servings
        </p>
        <img class="recipe_pic" src="{{recipe.image}}"/>
        <ul>
            <h2 class="ingredient_label">Ingredients:</h2>

            {%for ingredient in recipe.ingredientLines%}
            <li class="ingredient"> {{ingredient}}</li>
            {% endfor %}
        </ul>
    {% endfor %}
    </section>
</body>

</html>